### DISCUSSION TITLE
Cannot start lemonldap container: increase server_names_bucket_hash_size 32

### DISCUSSION THREAD

**Discussion by radokristof** [nfrastack/container-lemonldap#38] [Q&A] [answered]
Hi all,

I'm receiving the following error when I try to start the container:
`nginx: [emerg] could not build server_names_hash, you should increase server_names_hash_bucket_size: 32`

As I read, this might mean that the domain names are too long. I have tried to shorten them, same error.
Also I have tried modifying nginx config in place temporarily, then error is gone, but lemonldap shows an error page after startup.

`docker-compose.yml`:
```
  lemonldap:
    image: tiredofit/lemonldap:2.0-alpine-latest
    container_name: auth_lemonldap
    volumes:
      - ./data/lemonldap/etc/lemonldap-ng:/etc/lemonldap-ng
      - ./data/lemonldap/var/lib/lemonldap-ng:/var/lib/lemonldap-ng
      - ./data/lemonldap/logs:/www/logs
      - ./data/lemonldap/assets/custom:/assets/custom
    labels:
      caddy: "*.sso.example.com, sso.example.com"
      caddy.reverse_proxy: "{{ upstreams 80 }}"
      caddy.tls.dns:
    networks:
      - default
      - caddy
    environment:
      - TIMEZONE=Europe/Budapest
      - CONTAINER_NAME=auth_lemonldap
      - SETUP_TYPE=AUTO
      - API_HOSTNAME=api.manager.sso.example.com
      - MANAGER_HOSTNAME=manager.sso.example.com
      - PORTAL_HOSTNAME=sso.example.com
      - HANDLER_HOSTNAME=handler.sso.example.com
      - LOG_TYPE=FILE
      - LOG_LEVEL=debug
      - NGINX_SET_REAL_IP_FROM=192.168.0.0/16
    restart: always
    depends_on:
      - openldap
```
